name: GitHub Actions Demo
on: 
  push:
    branches:
      - main
    paths-ignore: .github/**
  pull_request:
    branches:
      - main
  workflow_dispatch: 
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1 
      - run: |
          echo "triggered by  ${{ github.event_name }}"
          echo " my branch is  ${{ github.ref }}"
          tree
  Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: test
    
    steps:
      - run: echo "testing... "
  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: load-test
       
    steps:
      - run: echo "testing... "
  Production:
    runs-on: ubuntu-latest
    needs: [Test,Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "testing 1... "
          sleep 10

      - run: |
          echo "testing 2... "
          sleep 10

      - run: |
          echo "testing 3... "
          sleep 10
